service: cloundFront-lambdaEdge
provider:
  name: aws
  runtime: nodejs10.x
  profile: seonghyeon
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:GetObject"
      Resource:
        - 'arn:aws:s3:::cloudfront-lambdaedge/*'

functions:
  originRequest:
    handler: index.handler
    events:
      - cloudFront:
          eventType: origin-request
          origin: s3://cloudfront-lambdaedge.s3.amazonaws.com
