service: cloundFront-lambdaEdge
provider:
  name: aws
  runtime: nodejs10.x
  profile: seonghyeon

functions:
  cfLambda:
    handler: index.handler
    events:
      - cloudFront:
          eventType: viewer-response
          origin: s3://cloudfront-lambdaedge.s3.amazonaws.com
